## See more docs at https://github.com/jenkinsci/docker/blob/master/README.md
version: "3.5"

services:
    jenkins:
        container_name: jenkins-2.107.1
        image: jenkins/jenkins:2.107.1
        ports:
            - 127.0.0.1:8080:8080
            - 127.0.0.1:50000:50000
        restart: always
        volumes:
            - data:/var/jenkins_home

volumes:
    data:
