concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  validate:
    # temp disable via 'if'
    if: startsWith(github.head_ref, 'opentofu/')
    runs-on: ubuntu-latest
    steps:
      - uses: opentofu/setup-opentofu@e95ccdd20623115bfd7d47df14a3250d6066a9d0 # v1.0.7
        with:
          tofu_version: 1.11.2 # renovate: datasource=github-releases depName=opentofu/opentofu packageName=opentofu/opentofu
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false
      - name: Apply terraform fmt and find unformatted files
        run: |
          bash -ex .github/opentofu-fmt.sh
          bash -ex .github/opentofu-validate.sh
    timeout-minutes: 20
name: opentofu-checks
on:
  pull_request:
    paths:
      - .github/opentofu-fmt.sh
      - .github/opentofu-validate.sh
      - .github/tf.sh
      - .github/workflows/opentofu-checks.yml
      - '**.otf'
      - '**.tf'
